// <auto-generated />
using System;
using Mavrynt.Modules.Users.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mavrynt.Modules.Users.Infrastructure.Migrations;

[DbContext(typeof(UsersDbContext))]
[Migration("20260430000002_AddRequiresPasswordChangeAndAdminSeed")]
partial class AddRequiresPasswordChangeAndAdminSeed
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Mavrynt.Modules.Users.Infrastructure.Audit.AuditEvent", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<string>("Email")
                .HasMaxLength(254)
                .HasColumnType("character varying(254)")
                .HasColumnName("email");

            b.Property<string>("EventType")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)")
                .HasColumnName("event_type");

            b.Property<string>("IpAddress")
                .HasMaxLength(45)
                .HasColumnType("character varying(45)")
                .HasColumnName("ip_address");

            b.Property<string>("Metadata")
                .HasColumnType("jsonb")
                .HasColumnName("metadata");

            b.Property<DateTimeOffset>("OccurredAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("occurred_at");

            b.Property<string>("Source")
                .HasMaxLength(64)
                .HasColumnType("character varying(64)")
                .HasColumnName("source");

            b.Property<string>("UserAgent")
                .HasMaxLength(512)
                .HasColumnType("character varying(512)")
                .HasColumnName("user_agent");

            b.Property<Guid?>("UserId")
                .HasColumnType("uuid")
                .HasColumnName("user_id");

            b.HasKey("Id");

            b.HasIndex("EventType")
                .HasDatabaseName("ix_audit_events_event_type");

            b.HasIndex("OccurredAt")
                .HasDatabaseName("ix_audit_events_occurred_at");

            b.HasIndex("UserId")
                .HasDatabaseName("ix_audit_events_user_id");

            b.ToTable("audit_events", "users");
        });

        modelBuilder.Entity("Mavrynt.Modules.Users.Domain.Entities.User", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<string>("DisplayName")
                .HasMaxLength(120)
                .HasColumnType("character varying(120)")
                .HasColumnName("display_name");

            b.Property<string>("Email")
                .IsRequired()
                .HasMaxLength(254)
                .HasColumnType("character varying(254)")
                .HasColumnName("email");

            b.Property<DateTimeOffset?>("PasswordChangedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("password_changed_at");

            b.Property<string>("PasswordHash")
                .IsRequired()
                .HasMaxLength(1024)
                .HasColumnType("character varying(1024)")
                .HasColumnName("password_hash");

            b.Property<bool>("RequiresPasswordChange")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasDefaultValue(false)
                .HasColumnName("requires_password_change");

            b.Property<string>("Role")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)")
                .HasColumnName("role");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)")
                .HasColumnName("status");

            b.Property<DateTimeOffset?>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");

            b.HasKey("Id");

            b.HasIndex("Email")
                .IsUnique()
                .HasDatabaseName("ix_users_email");

            b.ToTable("users", "users");
        });
#pragma warning restore 612, 618
    }
}
