// <auto-generated />
using System;
using Mavrynt.Modules.FeatureManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mavrynt.Modules.FeatureManagement.Infrastructure.Migrations;

[DbContext(typeof(FeatureManagementDbContext))]
[Migration("20260429000002_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Mavrynt.Modules.FeatureManagement.Domain.Entities.FeatureFlag", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<string>("Description")
                .HasMaxLength(1024)
                .HasColumnType("character varying(1024)")
                .HasColumnName("description");

            b.Property<bool>("IsEnabled")
                .HasColumnType("boolean")
                .HasColumnName("is_enabled");

            b.Property<string>("Key")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("key");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("name");

            b.Property<DateTimeOffset?>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");

            b.HasKey("Id");

            b.HasIndex("Key")
                .IsUnique()
                .HasDatabaseName("ix_feature_flags_key");

            b.ToTable("feature_flags", "feature_management");
        });
#pragma warning restore 612, 618
    }
}
