// <auto-generated />
using System;
using Mavrynt.Modules.Notifications.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mavrynt.Modules.Notifications.Infrastructure.Migrations;

[DbContext(typeof(NotificationsDbContext))]
[Migration("20260430000001_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Mavrynt.Modules.Notifications.Domain.Entities.SmtpSettings", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<string>("Host")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("host");

            b.Property<bool>("IsEnabled")
                .HasColumnType("boolean")
                .HasColumnName("is_enabled");

            b.Property<int>("Port")
                .HasColumnType("integer")
                .HasColumnName("port");

            b.Property<string>("ProtectedPassword")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("protected_password");

            b.Property<string>("ProviderName")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("provider_name");

            b.Property<string>("SenderEmail")
                .IsRequired()
                .HasMaxLength(320)
                .HasColumnType("character varying(320)")
                .HasColumnName("sender_email");

            b.Property<string>("SenderName")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("sender_name");

            b.Property<DateTimeOffset?>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");

            b.Property<bool>("UseSsl")
                .HasColumnType("boolean")
                .HasColumnName("use_ssl");

            b.Property<string>("Username")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("username");

            b.HasKey("Id");

            b.ToTable("smtp_settings", "notifications");
        });

        modelBuilder.Entity("Mavrynt.Modules.Notifications.Domain.Entities.EmailTemplate", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<string>("Description")
                .HasMaxLength(1024)
                .HasColumnType("character varying(1024)")
                .HasColumnName("description");

            b.Property<string>("DisplayName")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("display_name");

            b.Property<string>("HtmlBodyTemplate")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("html_body_template");

            b.Property<bool>("IsEnabled")
                .HasColumnType("boolean")
                .HasColumnName("is_enabled");

            b.Property<string>("Key")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("template_key");

            b.Property<string>("SubjectTemplate")
                .IsRequired()
                .HasMaxLength(512)
                .HasColumnType("character varying(512)")
                .HasColumnName("subject_template");

            b.Property<string>("TextBodyTemplate")
                .HasColumnType("text")
                .HasColumnName("text_body_template");

            b.Property<DateTimeOffset?>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");

            b.HasKey("Id");

            b.HasIndex("Key")
                .IsUnique()
                .HasDatabaseName("ix_email_templates_template_key");

            b.ToTable("email_templates", "notifications");
        });
#pragma warning restore 612, 618
    }
}
