// <auto-generated />
using System;
using Mavrynt.Modules.Audit.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mavrynt.Modules.Audit.Infrastructure.Migrations;

[DbContext(typeof(AuditDbContext))]
[Migration("20260429000001_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Mavrynt.Modules.Audit.Domain.Entities.AuditLogEntry", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<string>("Action")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("action");

            b.Property<Guid?>("ActorUserId")
                .HasColumnType("uuid")
                .HasColumnName("actor_user_id");

            b.Property<string>("MetadataJson")
                .HasColumnType("jsonb")
                .HasColumnName("metadata_json");

            b.Property<DateTimeOffset>("OccurredAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("occurred_at");

            b.Property<string>("ResourceId")
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("resource_id");

            b.Property<string>("ResourceType")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("resource_type");

            b.HasKey("Id");

            b.HasIndex("Action")
                .HasDatabaseName("ix_audit_log_entries_action");

            b.HasIndex("ActorUserId")
                .HasDatabaseName("ix_audit_log_entries_actor_user_id");

            b.HasIndex("OccurredAt")
                .HasDatabaseName("ix_audit_log_entries_occurred_at");

            b.HasIndex("ResourceType", "ResourceId")
                .HasDatabaseName("ix_audit_log_entries_resource");

            b.ToTable("audit_log_entries", "audit");
        });
#pragma warning restore 612, 618
    }
}
